package main

var regionMap = map[string]string{
	"Africa":                  "region_114",
	"Americas":                "region_402",
	"Andhra Pradesh":          "region_107",
	"Angola":                  "region_185",
	"Argentina":               "region_91",
	"Asia":                    "region_115",
	"Australia":               "region_73",
	"Australia & New Zealand": "region_116",
	"Austria":                 "region_293",
	"Bahrain":                 "region_252",
	"Belgium":                 "region_295",
	"Benin":                   "region_188",
	"Bihar":                   "region_78",
	"Bolivia":                 "region_394",
	"Brazil":                  "region_92",
	"Bulgaria":                "region_296",
	"Burkina Faso":            "region_186",
	"Cambodia":                "region_267",
	"Canada":                  "region_98",
	"Central Asia":            "region_409",
	"Central India":           "region_86",
	"Chhattisgarh":            "region_76",
	"Chile":                   "region_395",
	"Colombia":                "region_93",
	"Costa Rica":              "region_344",
	"Croatia":                 "region_306",
	"Cuba":                    "region_345",
	"Curaçao":                 "region_420",
	"Czech Republic":          "region_298",
	"Delhi":                   "region_181",
	"Denmark":                 "region_299",
	"Dominican Republic":      "region_347",
	"Eastern Africa":          "region_404",
	"Eastern Asia":            "region_410",
	"Eastern Europe":          "region_123",
	"Eastern India":           "region_87",
	"Ecuador":                 "region_94",
	"Egypt":                   "region_198",
	"El Salvador":             "region_364",
	"Estonia":                 "region_300",
	"Ethiopia":                "region_201",
	"Europe":                  "region_117",
	"Fiji":                    "region_372",
	"Finland":                 "region_301",
	"France":                  "region_81",
	"French Polynesia":        "region_382",
	"Germany":                 "region_82",
	"Ghana":                   "region_203",
	"Greece":                  "region_305",
	"Guatemala":               "region_351",
	"Gujarat":                 "region_112",
	"Haiti":                   "region_353",
	"Haryana":                 "region_100",
	"Himachal Pradesh":        "region_101",
	"Honduras":                "region_352",
	"Hong Kong":               "region_260",
	"Hungary":                 "region_307",
	"India":                   "region_118",
	"Indonesia":               "region_184",
	"Iran":                    "region_264",
	"Ireland":                 "region_308",
	"Israel":                  "region_261",
	"Italy":                   "region_311",
	"Jammu & Kashmir":         "region_102",
	"Japan":                   "region_179",
	"Karnataka":               "region_108",
	"Kenya":                   "region_208",
	"Kerala":                  "region_109",
	"Kyrgyzstan":              "region_266",
	"Latin America":           "region_119",
	"Latvia":                  "region_316",
	"Lebanon":                 "region_273",
	"Liberia":                 "region_210",
	"Lithuania":               "region_314",
	"Macedonia (FYROM)":       "region_320",
	"Madhya Pradesh":          "region_77",
	"Maharashtra":             "region_113",
	"Malaysia":                "region_183",
	"Mali":                    "region_215",
	"Mauritius":               "region_217",
	"Melanesia":               "region_414",
	"Mexico":                  "region_95",
	"Micronesian Region":      "region_415",
	"Middle Africa":           "region_405",
	"Mizoram":                 "region_127",
	"Mongolia":                "region_274",
	"Morocco":                 "region_213",
	"Mozambique":              "region_219",
	"Myanmar":                 "region_66",
	"Namibia":                 "region_220",
	"Nepal":                   "region_67",
	"Netherlands":             "region_322",
	"New Caledonia":           "region_378",
	"New Zealand":             "region_74",
	"Nicaragua":               "region_360",
	"Nigeria":                 "region_222",
	"North America":           "region_121",
	"Northern Africa":         "region_406",
	"Northern Europe":         "region_124",
	"Northern India":          "region_88",
	"Norway":                  "region_323",
	"Oceania":                 "region_403",
	"Oman":                    "region_277",
	"Orissa":                  "region_180",
	"Palestine":               "region_280",
	"Panama":                  "region_361",
	"Paraguay":                "region_399",
	"Peru":                    "region_96",
	"Philippines":             "region_278",
	"Poland":                  "region_324",
	"Polynesia":               "region_416",
	"Portugal":                "region_325",
	"Puerto Rico":             "region_363",
	"Punjab":                  "region_103",
	"Rajasthan":               "region_104",
	"Romania":                 "region_326",
	"Russia":                  "region_328",
	"Rwanda":                  "region_224",
	"Réunion":                 "region_223",
	"Serbia":                  "region_327",
	"Sikkim":                  "region_128",
	"Singapore":               "region_283",
	"Slovenia":                "region_330",
	"South Africa":            "region_239",
	"South Korea":             "region_269",
	"South-Eastern Asia":      "region_412",
	"Southern Africa":         "region_407",
	"Southern Asia":           "region_411",
	"Southern Europe":         "region_126",
	"Southern India":          "region_89",
	"Spain":                   "region_83",
	"Sri Lanka":               "region_68",
	"Sudan":                   "region_226",
	"Suriname":                "region_400",
	"Swaziland":               "region_232",
	"Sweden":                  "region_329",
	"Switzerland":             "region_84",
	"Taiwan":                  "region_69",
	"Tamil Nadu":              "region_110",
	"Tanzania":                "region_236",
	"Telangana":               "region_418",
	"Telugu Land":             "region_426",
	"Thailand":                "region_70",
	"Tripura":                 "region_79",
	"Tunisia":                 "region_235",
	"Turkey":                  "region_334",
	"Uganda":                  "region_237",
	"Ukraine":                 "region_335",
	"United Arab Emirates":    "region_247",
	"United Kingdom":          "region_85",
	"United States":           "region_99",
	"Uruguay":                 "region_401",
	"Uttar Pradesh":           "region_105",
	"Uttarakhand":             "region_106",
	"Uzbekistan":              "region_288",
	"Venezuela":               "region_97",
	"Vietnam":                 "region_289",
	"West Bengal":             "region_80",
	"Western Africa":          "region_408",
	"Western Asia":            "region_413",
	"Western Europe":          "region_125",
	"Western India":           "region_90",
	"World":                   "region_122",
	"Zimbabwe":                "region_241",
}
